/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUICmp;

import EmployeeData.EmployeeData;
import EmployeeData.employeeDirectory;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Shalini shree
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    employeeDirectory directory;
    public CreateJPanel(employeeDirectory directory) {
        initComponents();
        this.directory = directory;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblCreateEmployee = new javax.swing.JLabel();
        LblEmployeeFname = new javax.swing.JLabel();
        txtemployeeFname = new javax.swing.JTextField();
        LblEmployeeLname = new javax.swing.JLabel();
        txtEmployeeLname = new javax.swing.JTextField();
        LblEmployeeID = new javax.swing.JLabel();
        txtEmployeeID = new javax.swing.JTextField();
        LblAge = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        Lblstartdate = new javax.swing.JLabel();
        startdate = new com.toedter.calendar.JDateChooser();
        jcontactinfo = new javax.swing.JLabel();
        LblTelephone = new javax.swing.JLabel();
        txtTelephone = new javax.swing.JTextField();
        LblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        Lblgender = new javax.swing.JLabel();
        txtgender = new javax.swing.JTextField();
        LblEmployeelevel = new javax.swing.JLabel();
        txtEmployeelevel = new javax.swing.JTextField();
        Lblteaminfo = new javax.swing.JLabel();
        txtteaminfo = new javax.swing.JTextField();
        LblPosition = new javax.swing.JLabel();
        ProfilePhoto = new javax.swing.JLabel();
        txtposition = new javax.swing.JTextField();
        LblProfilePhoto = new javax.swing.JLabel();
        BtnAttchProfileImg = new javax.swing.JButton();
        BtnSave = new javax.swing.JButton();
        LblFnameErr = new javax.swing.JLabel();
        LblLnameErr = new javax.swing.JLabel();
        LblEmailErr = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));
        setPreferredSize(new java.awt.Dimension(800, 700));

        LblCreateEmployee.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        LblCreateEmployee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblCreateEmployee.setText("Create Employee Profile");

        LblEmployeeFname.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LblEmployeeFname.setText("Employee First Name");

        txtemployeeFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemployeeFnameActionPerformed(evt);
            }
        });
        txtemployeeFname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtemployeeFnameKeyPressed(evt);
            }
        });

        LblEmployeeLname.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LblEmployeeLname.setText("Employee Last Name");

        txtEmployeeLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeLnameActionPerformed(evt);
            }
        });
        txtEmployeeLname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmployeeLnameKeyPressed(evt);
            }
        });

        LblEmployeeID.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LblEmployeeID.setText("Employee ID");

        txtEmployeeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeIDActionPerformed(evt);
            }
        });

        LblAge.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LblAge.setText("Age");

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        txtAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAgeKeyPressed(evt);
            }
        });

        Lblstartdate.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        Lblstartdate.setText("Start Date");

        jcontactinfo.setFont(new java.awt.Font("Georgia", 1, 15)); // NOI18N
        jcontactinfo.setText("Contact Information:");

        LblTelephone.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LblTelephone.setText("Telephone");

        txtTelephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelephoneActionPerformed(evt);
            }
        });
        txtTelephone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelephoneKeyPressed(evt);
            }
        });

        LblEmail.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LblEmail.setText("Email");

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailKeyPressed(evt);
            }
        });

        Lblgender.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        Lblgender.setText("Gender");

        txtgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgenderActionPerformed(evt);
            }
        });

        LblEmployeelevel.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LblEmployeelevel.setText("Employee level");

        txtEmployeelevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeelevelActionPerformed(evt);
            }
        });
        txtEmployeelevel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmployeelevelKeyPressed(evt);
            }
        });

        Lblteaminfo.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        Lblteaminfo.setText("Team Information");

        txtteaminfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtteaminfoActionPerformed(evt);
            }
        });

        LblPosition.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LblPosition.setText("Position");

        ProfilePhoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtposition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpositionActionPerformed(evt);
            }
        });

        LblProfilePhoto.setFont(new java.awt.Font("Georgia", 0, 13)); // NOI18N
        LblProfilePhoto.setText("Photo");

        BtnAttchProfileImg.setFont(new java.awt.Font("Georgia", 0, 13)); // NOI18N
        BtnAttchProfileImg.setText("Attach");
        BtnAttchProfileImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAttchProfileImgActionPerformed(evt);
            }
        });

        BtnSave.setText("Save");
        BtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveActionPerformed(evt);
            }
        });

        LblFnameErr.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        LblFnameErr.setForeground(new java.awt.Color(255, 51, 51));

        LblLnameErr.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        LblLnameErr.setForeground(new java.awt.Color(255, 51, 51));

        LblEmailErr.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        LblEmailErr.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LblCreateEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(LblEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(455, 455, 455))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblEmployeeFname)
                            .addComponent(LblEmployeelevel)
                            .addComponent(Lblstartdate)
                            .addComponent(LblTelephone)
                            .addComponent(Lblgender))
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(startdate, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                                .addComponent(BtnSave)
                                .addGap(612, 612, 612))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtemployeeFname, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LblFnameErr, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtEmployeelevel, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtgender, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Lblteaminfo)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtteaminfo, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(LblAge)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(LblEmployeeLname)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                                                .addComponent(txtEmployeeLname, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addComponent(LblLnameErr, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(LblEmail)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(LblPosition)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtposition, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LblEmailErr, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)))
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGap(225, 225, 225)
                                .addComponent(jcontactinfo)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(488, 488, 488)
                        .addComponent(ProfilePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(546, 546, 546)
                        .addComponent(LblProfilePhoto)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(530, 530, 530)
                .addComponent(BtnAttchProfileImg)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblCreateEmployee)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblProfilePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProfilePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(BtnAttchProfileImg)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LblFnameErr, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LblLnameErr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LblEmployeeFname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtemployeeFname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtgender, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lblgender))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmployeelevel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblEmployeelevel)
                            .addComponent(Lblteaminfo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(startdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lblstartdate, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblEmployeeID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmployeeLname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblEmployeeLname, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblAge))
                        .addGap(18, 18, 18)
                        .addComponent(txtteaminfo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtposition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblPosition))
                        .addGap(6, 6, 6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jcontactinfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LblEmail)
                        .addComponent(txtTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LblTelephone))
                    .addComponent(LblEmailErr, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(BtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(219, 219, 219))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmployeeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeIDActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void BtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveActionPerformed
        // TODO add your handling code here:
        if (txtemployeeFname.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please enter Employee First Name");
        }
        if (txtemployeeFname.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please enter Employee Last Name");
        }
        if (txtEmployeeID.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please enter Employee ID");
        }
        if (txtAge.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please enter your age");
        }
        if (txtEmail.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please enter Email");
        }
    else{
        EmployeeData ed = directory.addNewDetails();
        
        ed.setemployeeFname(txtemployeeFname.getText());
        ed.setemployeeLname(txtEmployeeLname.getText());
        ed.setemployeeID(txtEmployeeID.getText());
        ed.setemployeeAge(txtAge.getText());
        ed.setEmail(txtEmail.getText());
        ed.setemployeelevel(txtEmployeelevel.getText());
        ed.setteaminfo(txtteaminfo.getText());
        ed.setstartdate(startdate.getDate());      
        ed.setTelephone(txtTelephone.getText());
        ed.setposition(txtposition.getText());
        ed.setgender(txtgender.getText());
//        ProfilePhoto.setIcon(new ImageIcon(image));
        ed.setPhotoID((ImageIcon) ProfilePhoto.getIcon());
        

        
        JOptionPane.showMessageDialog(this, "Employee Profile Saved");
        }
        if (!txtTelephone.getText().equals("")){
        //try {   
           // persondata.setTelephone(Integer.parseInt(txtTelephone.getText()));
         //} catch (NumberFormatException nfe) {
            // Handle the condition when str is not a number.
         //}
        }
        else{
         JOptionPane.showMessageDialog(this, "Please enter Telephone number");
        }
    }//GEN-LAST:event_BtnSaveActionPerformed

    private void txtemployeeFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemployeeFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemployeeFnameActionPerformed

    private void txtEmployeeLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeLnameActionPerformed

    private void BtnAttchProfileImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAttchProfileImgActionPerformed
    JFileChooser browseImageFile = new JFileChooser();
    //EmployeeData ed = directory.addNewDetails();
    
    FileNameExtensionFilter filter = new FileNameExtensionFilter("IMAGES", "png", "jpg","jpeg");
    browseImageFile.addChoosableFileFilter(filter);
    int showOpenDialogue = browseImageFile.showOpenDialog(null);
    
    if (showOpenDialogue ==JFileChooser.APPROVE_OPTION){
        File selectedImageFile = browseImageFile.getSelectedFile();
        String selectedImagePath = selectedImageFile.getAbsolutePath();
        ImageIcon Img = new ImageIcon(selectedImagePath);
        Image image = Img.getImage().getScaledInstance(ProfilePhoto.getWidth(), ProfilePhoto.getHeight(), Image.SCALE_SMOOTH);
        ProfilePhoto.setIcon(new ImageIcon(image));
        //ed.setPhotoID(new ImageIcon(image));
        
    }
    }//GEN-LAST:event_BtnAttchProfileImgActionPerformed

    private void txtTelephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelephoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelephoneActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgenderActionPerformed

    private void txtEmployeelevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeelevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeelevelActionPerformed

    private void txtteaminfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtteaminfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtteaminfoActionPerformed

    private void txtTelephoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelephoneKeyPressed
        // TODO add your handling code here: 
        String Telephone = txtTelephone.getText();
        int length = Telephone.length();
        char c = evt.getKeyChar();
        
        if (evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            if (length<10){
                txtTelephone.setEditable(true);
                //txtTelephone.setKeyChar(Telephone);
            }else{
                txtTelephone.setEditable(false);
            }
        }else {
            if (evt.getExtendedKeyCode()== KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()== KeyEvent.VK_DELETE){
                txtTelephone.setEditable(true);
            }else{
                txtTelephone.setEditable(false);   
            }
        }
    }//GEN-LAST:event_txtTelephoneKeyPressed

    private void txtemployeeFnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtemployeeFnameKeyPressed
String PATTERN = "^[a-zA-Z]{0,30}$";
Pattern pt = Pattern.compile(PATTERN);
Matcher mtch = pt.matcher(txtemployeeFname.getText());
    if (!mtch.matches()){
     LblFnameErr.setText("Naming Incorrect");
    }else{
    LblFnameErr.setText(null);
    }
    }//GEN-LAST:event_txtemployeeFnameKeyPressed

    private void txtEmployeeLnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmployeeLnameKeyPressed
  String PATTERN = "^[a-zA-Z]{0,30}$";
Pattern pt = Pattern.compile(PATTERN);
Matcher mtch = pt.matcher(txtEmployeeLname.getText());
    if (!mtch.matches()){
     LblLnameErr.setText("Naming Incorrect");
    }else{
    LblLnameErr.setText(null);
    }
   
    }//GEN-LAST:event_txtEmployeeLnameKeyPressed

    private void txtAgeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeKeyPressed

//    String PATTERN = "^[a-zA-Z]{0,10}$";
//Pattern pt = Pattern.compile(PATTERN);
//Matcher mtch = pt.matcher(txtAge.getText());
//if (!mtch.matches()){
//    LblAge.setText("Age Incorrect");
//    }else{
//    LblAge.setText(null);
//    }
    }//GEN-LAST:event_txtAgeKeyPressed

    private void txtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyPressed
    String PATTERN = "^[a-zA-Z0-9]{0,30}[@][a-zA-Z]{0,10}[.][a-zA-Z]{0,5}$";
Pattern pt = Pattern.compile(PATTERN);
Matcher mtch = pt.matcher(txtEmail.getText());
if (!mtch.matches()){
     LblEmailErr.setText("Email Incorrect");
    }else{
    LblEmailErr.setText(null);
    }
    }//GEN-LAST:event_txtEmailKeyPressed

    private void txtEmployeelevelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmployeelevelKeyPressed
            //TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeelevelKeyPressed

    private void txtpositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpositionActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAttchProfileImg;
    private javax.swing.JButton BtnSave;
    private javax.swing.JLabel LblAge;
    private javax.swing.JLabel LblCreateEmployee;
    private javax.swing.JLabel LblEmail;
    private javax.swing.JLabel LblEmailErr;
    private javax.swing.JLabel LblEmployeeFname;
    private javax.swing.JLabel LblEmployeeID;
    private javax.swing.JLabel LblEmployeeLname;
    private javax.swing.JLabel LblEmployeelevel;
    private javax.swing.JLabel LblFnameErr;
    private javax.swing.JLabel LblLnameErr;
    private javax.swing.JLabel LblPosition;
    private javax.swing.JLabel LblProfilePhoto;
    private javax.swing.JLabel LblTelephone;
    private javax.swing.JLabel Lblgender;
    private javax.swing.JLabel Lblstartdate;
    private javax.swing.JLabel Lblteaminfo;
    private javax.swing.JLabel ProfilePhoto;
    private javax.swing.JLabel jcontactinfo;
    private com.toedter.calendar.JDateChooser startdate;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmployeeID;
    private javax.swing.JTextField txtEmployeeLname;
    private javax.swing.JTextField txtEmployeelevel;
    private javax.swing.JTextField txtTelephone;
    private javax.swing.JTextField txtemployeeFname;
    private javax.swing.JTextField txtgender;
    private javax.swing.JTextField txtposition;
    private javax.swing.JTextField txtteaminfo;
    // End of variables declaration//GEN-END:variables
}
