/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUICmp;

import EmployeeData.employeeDirectory;

/**
 *
 * @author Shalini Shree
 */
public class MainJFrame extends javax.swing.JFrame {
employeeDirectory directory;
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        directory = new employeeDirectory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPane = new javax.swing.JSplitPane();
        ButtonArea = new javax.swing.JPanel();
        BtnCreateEmployee = new javax.swing.JButton();
        BtnDisplayEmployee = new javax.swing.JButton();
        DataArea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ButtonArea.setBackground(new java.awt.Color(38, 38, 85));

        BtnCreateEmployee.setBackground(new java.awt.Color(153, 153, 255));
        BtnCreateEmployee.setText("Create Employee Profile");
        BtnCreateEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCreateEmployeeActionPerformed(evt);
            }
        });

        BtnDisplayEmployee.setBackground(new java.awt.Color(153, 153, 255));
        BtnDisplayEmployee.setText("Display Employee Profile");
        BtnDisplayEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDisplayEmployeeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ButtonAreaLayout = new javax.swing.GroupLayout(ButtonArea);
        ButtonArea.setLayout(ButtonAreaLayout);
        ButtonAreaLayout.setHorizontalGroup(
            ButtonAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ButtonAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ButtonAreaLayout.createSequentialGroup()
                        .addComponent(BtnDisplayEmployee)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(BtnCreateEmployee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        ButtonAreaLayout.setVerticalGroup(
            ButtonAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonAreaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(BtnCreateEmployee)
                .addGap(18, 18, 18)
                .addComponent(BtnDisplayEmployee)
                .addContainerGap(532, Short.MAX_VALUE))
        );

        SplitPane.setLeftComponent(ButtonArea);

        DataArea.setBackground(new java.awt.Color(8, 71, 135));

        javax.swing.GroupLayout DataAreaLayout = new javax.swing.GroupLayout(DataArea);
        DataArea.setLayout(DataAreaLayout);
        DataAreaLayout.setHorizontalGroup(
            DataAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 514, Short.MAX_VALUE)
        );
        DataAreaLayout.setVerticalGroup(
            DataAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 636, Short.MAX_VALUE)
        );

        SplitPane.setRightComponent(DataArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCreateEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCreateEmployeeActionPerformed
        // TODO add your handling code here:
        
       CreateJPanel createpanel = new CreateJPanel(directory);
       SplitPane.setRightComponent(createpanel);
    }//GEN-LAST:event_BtnCreateEmployeeActionPerformed

    private void BtnDisplayEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDisplayEmployeeActionPerformed
        // TODO add your handling code here:
        
        ReadJPanel displaypanel = new ReadJPanel(directory);
        SplitPane.setRightComponent(displaypanel);
    }//GEN-LAST:event_BtnDisplayEmployeeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCreateEmployee;
    private javax.swing.JButton BtnDisplayEmployee;
    private javax.swing.JPanel ButtonArea;
    private javax.swing.JPanel DataArea;
    private javax.swing.JSplitPane SplitPane;
    // End of variables declaration//GEN-END:variables
}
