/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUICmp;

import EmployeeData.EmployeeData;
import EmployeeData.employeeDirectory;
import java.awt.Image;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shalini Shree
 */
public class ReadJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DisplayJPanel
     */
    
    
    employeeDirectory directory;
    public ReadJPanel(employeeDirectory directory) {
        initComponents();
        this.directory = directory;
        
        employeedirectory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblCreateEmployee = new javax.swing.JLabel();
        LblEmployeeFname = new javax.swing.JLabel();
        txtEmployeeFname = new javax.swing.JTextField();
        LblEmployeeLname = new javax.swing.JLabel();
        txtEmployeeLname = new javax.swing.JTextField();
        LblEmployeeID = new javax.swing.JLabel();
        txtEmployeeID = new javax.swing.JTextField();
        LblAge = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        Lblstartdate = new javax.swing.JLabel();
        txtstartdate = new javax.swing.JTextField();
        LblTelephone = new javax.swing.JLabel();
        txtTelephone = new javax.swing.JTextField();
        LblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        Lblgender = new javax.swing.JLabel();
        txtgender = new javax.swing.JTextField();
        LblEmployeelevel = new javax.swing.JLabel();
        txtEmployeelevel = new javax.swing.JTextField();
        Lblteaminfo = new javax.swing.JLabel();
        txtteaminfo = new javax.swing.JTextField();
        LblPosition = new javax.swing.JLabel();
        txtPosition = new javax.swing.JTextField();
        LblProfilePhoto = new javax.swing.JLabel();
        ProfilePhoto = new javax.swing.JLabel();
        contactinformation = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblempdirectory = new javax.swing.JTable();
        View = new javax.swing.JButton();
        delete = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 255));

        LblCreateEmployee.setFont(new java.awt.Font("Georgia", 1, 15)); // NOI18N
        LblCreateEmployee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblCreateEmployee.setText("Display Employee Profile");

        LblEmployeeFname.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LblEmployeeFname.setText("Employee First Name");

        txtEmployeeFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeFnameActionPerformed(evt);
            }
        });

        LblEmployeeLname.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LblEmployeeLname.setText("Employee Last Name");

        txtEmployeeLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeLnameActionPerformed(evt);
            }
        });

        LblEmployeeID.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LblEmployeeID.setText("Employee ID");

        txtEmployeeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeIDActionPerformed(evt);
            }
        });

        LblAge.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LblAge.setText("Age");

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });

        Lblstartdate.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        Lblstartdate.setText("Start Date");

        txtstartdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstartdateActionPerformed(evt);
            }
        });

        LblTelephone.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LblTelephone.setText("Telephone");

        txtTelephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelephoneActionPerformed(evt);
            }
        });

        LblEmail.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LblEmail.setText("Email");

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        Lblgender.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        Lblgender.setText("Gender");

        txtgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgenderActionPerformed(evt);
            }
        });

        LblEmployeelevel.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LblEmployeelevel.setText("Employee Level");

        txtEmployeelevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeelevelActionPerformed(evt);
            }
        });

        Lblteaminfo.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        Lblteaminfo.setText("Team Information");

        txtteaminfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtteaminfoActionPerformed(evt);
            }
        });

        LblPosition.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LblPosition.setText("Position");

        txtPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPositionActionPerformed(evt);
            }
        });

        LblProfilePhoto.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LblProfilePhoto.setText("Photo");

        ProfilePhoto.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        contactinformation.setFont(new java.awt.Font("Georgia", 1, 15)); // NOI18N
        contactinformation.setText("Contact Information:");

        tblempdirectory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Employee ID", "Employee First Name", "Employee Name", "Level"
            }
        ));
        jScrollPane1.setViewportView(tblempdirectory);

        View.setText("View");
        View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewActionPerformed(evt);
            }
        });

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 64, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LblEmployeelevel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblEmployeeLname)
                            .addComponent(LblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lblteaminfo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmployeeLname, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtteaminfo, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(324, 324, 324))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LblCreateEmployee, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(contactinformation)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(LblEmployeeFname)
                                                        .addComponent(Lblgender))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(Lblstartdate, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(4, 4, 4)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtstartdate, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtgender, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtEmployeeFname, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtEmployeelevel, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(71, 71, 71)
                                        .addComponent(LblProfilePhoto)
                                        .addGap(39, 39, 39)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(ProfilePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(450, 450, 450)
                                                .addComponent(View)
                                                .addGap(18, 18, 18)
                                                .addComponent(delete))
                                            .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(LblTelephone)
                                                .addGap(82, 82, 82))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(62, 62, 62)
                                                .addComponent(LblEmployeeID)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addComponent(txtTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LblCreateEmployee)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(View)
                        .addComponent(delete))
                    .addComponent(LblProfilePhoto)
                    .addComponent(ProfilePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblEmployeeID))
                        .addGap(112, 112, 112))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblEmployeeLname)
                            .addComponent(txtEmployeeLname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmployeeFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblEmployeeFname, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(LblAge)
                                .addComponent(txtgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Lblgender))
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lblteaminfo)
                            .addComponent(txtteaminfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblPosition)
                            .addComponent(txtPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtstartdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lblstartdate, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblEmployeelevel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmployeelevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(contactinformation)
                        .addGap(14, 14, 14)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblTelephone)
                    .addComponent(LblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmployeeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeIDActionPerformed

    private void txtEmployeeFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeFnameActionPerformed

    private void txtEmployeeLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeLnameActionPerformed

    private void txtTelephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelephoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelephoneActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgenderActionPerformed

    private void txtPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPositionActionPerformed

    private void txtEmployeelevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeelevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeelevelActionPerformed

    private void txtteaminfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtteaminfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtteaminfoActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtstartdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstartdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstartdateActionPerformed

    private void ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblempdirectory.getSelectedRow();
        if (selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "SELECT A VALID ROW");
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) tblempdirectory.getModel();
        
        EmployeeData selectedEmployeeData = (EmployeeData) model.getValueAt(selectedRowIndex, 0);
        txtEmployeeFname.setText(selectedEmployeeData.getemployeeFname());
        txtEmployeeLname.setText(selectedEmployeeData.getemployeeLname());
        txtEmployeeID.setText(selectedEmployeeData.getemployeeID());
        txtEmail.setText(selectedEmployeeData.getEmail());
        txtAge.setText(selectedEmployeeData.getemployeeAge());
        txtgender.setText(selectedEmployeeData.getgender());
        txtteaminfo.setText(selectedEmployeeData.getteaminfo());
        txtPosition.setText(selectedEmployeeData.getposition());
        txtEmployeelevel.setText(selectedEmployeeData.getemployeelevel());
        //txtTelephone.setText(Integer.toString(persondata.getTelephone()));
        txtTelephone.setText(selectedEmployeeData.getTelephone());
        ProfilePhoto.setIcon(selectedEmployeeData.getPhotoID());
        txtstartdate.setText(selectedEmployeeData.getstartdate());
    }//GEN-LAST:event_ViewActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblempdirectory.getSelectedRow();
        if (selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please Select a Row to Delete.");
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) tblempdirectory.getModel();
        
        EmployeeData selectedEmployeeData = (EmployeeData) model.getValueAt(selectedRowIndex, 0);
        
        directory.deleteEmployeeDetails(selectedEmployeeData);
        
        JOptionPane.showMessageDialog(this, "Deleted Employee Details");
        
        employeedirectory();
    }//GEN-LAST:event_deleteActionPerformed




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblAge;
    private javax.swing.JLabel LblCreateEmployee;
    private javax.swing.JLabel LblEmail;
    private javax.swing.JLabel LblEmployeeFname;
    private javax.swing.JLabel LblEmployeeID;
    private javax.swing.JLabel LblEmployeeLname;
    private javax.swing.JLabel LblEmployeelevel;
    private javax.swing.JLabel LblPosition;
    private javax.swing.JLabel LblProfilePhoto;
    private javax.swing.JLabel LblTelephone;
    private javax.swing.JLabel Lblgender;
    private javax.swing.JLabel Lblstartdate;
    private javax.swing.JLabel Lblteaminfo;
    private javax.swing.JLabel ProfilePhoto;
    private javax.swing.JButton View;
    private javax.swing.JLabel contactinformation;
    private javax.swing.JButton delete;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblempdirectory;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmployeeFname;
    private javax.swing.JTextField txtEmployeeID;
    private javax.swing.JTextField txtEmployeeLname;
    private javax.swing.JTextField txtEmployeelevel;
    private javax.swing.JTextField txtPosition;
    private javax.swing.JTextField txtTelephone;
    private javax.swing.JTextField txtgender;
    private javax.swing.JTextField txtstartdate;
    private javax.swing.JTextField txtteaminfo;
    // End of variables declaration//GEN-END:variables

    
        private void DisplayEmployeeProfile() {
        txtEmployeeFname.setEditable(false);
        txtEmployeeLname.setEditable(false);
        txtEmployeeID.setEditable(false);
        txtTelephone.setEditable(false);
        txtEmail.setEditable(false);
        txtAge.setEditable(false);
        txtgender.setEditable(false);
        txtteaminfo.setEditable(false);
        txtPosition.setEditable(false);
        txtTelephone.setEditable(false);
        txtEmployeelevel.setEditable(false);  
        }
        
    
        private void employeedirectory(){
            DefaultTableModel model = (DefaultTableModel) tblempdirectory.getModel();
            model.setRowCount(0);
        
        for ( EmployeeData ed : directory.getdirectory()){
            Object[] row = new Object[4];
            row[0]= ed;
            row[1]= ed.getemployeeFname();
            row[2]= ed.getemployeeLname();
            row[3]= ed.getemployeeID();
            
            model.addRow(row);
        }
    } 
}
 
