/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import model.PersonHistory;
import model.SystemFiles;
import model.Encounterhistory;
import model.Person;
import ui.systemadmin;
 

/**
 *
 * @author shalinishree
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    
    PersonHistory personhistory;
    SystemFiles systemsys;
    Encounterhistory ehistory;
    String globalRole;
    
    public MainJFrame() {
        initComponents();
        systemsys = new SystemFiles();
        personhistory = new PersonHistory();
        ehistory = new Encounterhistory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        btnsystemadmin = new javax.swing.JButton();
        btnhospitaladmin = new javax.swing.JButton();
        btnpatient = new javax.swing.JButton();
        btncommadmin = new javax.swing.JButton();
        btndoctor = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();
        jusername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        jloginbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        controlPanel.setBackground(new java.awt.Color(255, 153, 51));
        controlPanel.setMaximumSize(new java.awt.Dimension(150, 598));
        controlPanel.setPreferredSize(new java.awt.Dimension(150, 598));

        btnsystemadmin.setText("SYSTEM ADMIN");
        btnsystemadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsystemadminActionPerformed(evt);
            }
        });

        btnhospitaladmin.setText("HOSPITAL ADMIN");
        btnhospitaladmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhospitaladminActionPerformed(evt);
            }
        });

        btnpatient.setText("PATIENT");
        btnpatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpatientActionPerformed(evt);
            }
        });

        btncommadmin.setText("COMM ADMIN");
        btncommadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncommadminActionPerformed(evt);
            }
        });

        btndoctor.setText("DOCTOR");
        btndoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndoctorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnpatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btncommadmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnsystemadmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnhospitaladmin, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
            .addComponent(btndoctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(btnsystemadmin)
                .addGap(18, 18, 18)
                .addComponent(btnhospitaladmin)
                .addGap(18, 18, 18)
                .addComponent(btncommadmin)
                .addGap(18, 18, 18)
                .addComponent(btnpatient)
                .addGap(18, 18, 18)
                .addComponent(btndoctor)
                .addContainerGap(278, Short.MAX_VALUE))
        );

        splitPane.setLeftComponent(controlPanel);
        controlPanel.getAccessibleContext().setAccessibleName("");

        workArea.setBackground(new java.awt.Color(255, 153, 51));
        workArea.setMaximumSize(new java.awt.Dimension(650, 598));
        workArea.setRequestFocusEnabled(false);
        workArea.setSize(new java.awt.Dimension(650, 598));

        jusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jusernameActionPerformed(evt);
            }
        });

        jLabel1.setText("Username: ");

        jLabel2.setText("Password:");

        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });

        jloginbtn.setText("LOGIN");
        jloginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jloginbtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Bangla MN", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("HOSPITAL SYSTEM");

        javax.swing.GroupLayout workAreaLayout = new javax.swing.GroupLayout(workArea);
        workArea.setLayout(workAreaLayout);
        workAreaLayout.setHorizontalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workAreaLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(workAreaLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(workAreaLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jusername, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(workAreaLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(workAreaLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(workAreaLayout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(jloginbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        workAreaLayout.setVerticalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workAreaLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addComponent(jusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(3, 3, 3)
                .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jloginbtn))
        );

        splitPane.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsystemadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsystemadminActionPerformed
        // TODO add your handling code here:
        
        globalRole = "SystemAdmin";
        splitPane.setRightComponent(workArea);

    }//GEN-LAST:event_btnsystemadminActionPerformed

    private void btnhospitaladminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhospitaladminActionPerformed
        // TODO add your handling code here:
        //PatientDir patientdir = new PatientDir(personhistory,ehistory);
        //splitPane.setRightComponent(patientdir);
        globalRole = "hospAdmin";
        splitPane.setRightComponent(workArea);
        
    }//GEN-LAST:event_btnhospitaladminActionPerformed

    private void btncommadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncommadminActionPerformed
        // TODO add your handling code here:
        globalRole = "commAdmin";
//        Encounter encounter = new Encounter(vhistory);
//        splitPane.setRightComponent(encounter);

          splitPane.setRightComponent(workArea);
    }//GEN-LAST:event_btncommadminActionPerformed

    private void btnpatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpatientActionPerformed
        // TODO add your handling code here:
        splitPane.setRightComponent(workArea);
//        Analysis analysis = new Analysis(vhistory);
//        splitPane.setRightComponent(analysis);
    }//GEN-LAST:event_btnpatientActionPerformed

    private void btndoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndoctorActionPerformed
        // TODO add your handling code here:
        splitPane.setRightComponent(workArea);
    }//GEN-LAST:event_btndoctorActionPerformed

    private void jusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jusernameActionPerformed

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed

    private void jloginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jloginbtnActionPerformed
        // TODO add your handling code here:
        String username = jusername.getText();
        String password = new String(jPassword.getPassword());     
        boolean flag = false;
        systemadmin sa = new systemadmin(globalRole);

        if(username.equals("") || password.equals(""))
            JOptionPane.showMessageDialog(this, "Please enter User Name and/or Password.");
        else
        {
            for(Person person : systemsys.getPersonHistoryList())
            {
                if(person.getUsername().equals(username) && person.getPassword().equals(password))
                {
                    flag = true;
                    
                    if(globalRole.equals("SystemAdmin") || globalRole.equals("hospAdmin") )
                        splitPane.setRightComponent(sa);
                    else if (globalRole.equals("commAdmin") )
                        splitPane.setRightComponent(new communityadmin(globalRole));
                    
                    break;
                }
            }
        }
        
        if(!flag)
            JOptionPane.showMessageDialog(this, "Please enter a valid user name and password.");
    }//GEN-LAST:event_jloginbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncommadmin;
    private javax.swing.JButton btndoctor;
    private javax.swing.JButton btnhospitaladmin;
    private javax.swing.JButton btnpatient;
    private javax.swing.JButton btnsystemadmin;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JButton jloginbtn;
    private javax.swing.JTextField jusername;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
