/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Encounterhistory;
import model.Encounter;

/**
 *
 * @author shalinishree
 */
public class systemadmin extends javax.swing.JPanel {

    Encounterhistory Encounterhistory;
    
    /**
     * Creates new form systemadmin
     */
    public systemadmin() {
        initComponents();
        Encounterhistory = new Encounterhistory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLandingPanel = new javax.swing.JPanel();
        hospitalSysAdminBtn = new javax.swing.JButton();
        patientSysAdminBtn = new javax.swing.JButton();
        encounterSysAdminBtn = new javax.swing.JButton();
        DoctorSysAdminBtn = new javax.swing.JButton();
        jHospitalSysAdmin = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        NewHospitalBtn = new javax.swing.JButton();
        DisplayHospitalBtn = new javax.swing.JButton();
        HospitalBackBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CityHospitalLbl = new javax.swing.JLabel();
        HospitalCommunityLbl = new javax.swing.JLabel();
        NewHospitalLbl = new javax.swing.JLabel();
        newHospitalTxt = new javax.swing.JTextField();
        NewHospitalSubmitbtn = new javax.swing.JButton();
        CityNewTxt = new javax.swing.JTextField();
        CommunityNewTxt = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        DeleteHospBtn = new javax.swing.JButton();
        EditHospBtn = new javax.swing.JButton();
        ViewHospBtn = new javax.swing.JButton();
        NewHospitalSubmitbtn1 = new javax.swing.JButton();
        CityHospitalLbl1 = new javax.swing.JLabel();
        HospitalCommunityLbl1 = new javax.swing.JLabel();
        NewHospitalLbl1 = new javax.swing.JLabel();
        newHospitalTxt1 = new javax.swing.JTextField();
        CommunityUpdateTxt = new javax.swing.JTextField();
        CityUpdateTxt = new javax.swing.JTextField();
        jDoctorSysAdmin = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel4 = new javax.swing.JPanel();
        NewdocBtn1 = new javax.swing.JButton();
        DisplaydocBtn = new javax.swing.JButton();
        docBackBtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        doc_nameLbl2 = new javax.swing.JLabel();
        doc_CityLbl2 = new javax.swing.JLabel();
        doc_CityCb2 = new javax.swing.JComboBox<>();
        doc_HospitalLbl2 = new javax.swing.JLabel();
        doc_HospitalTxt2 = new javax.swing.JTextField();
        doc_Submitbtn2 = new javax.swing.JButton();
        doc_nameTxt = new javax.swing.JTextField();
        doc_ageTxt9 = new javax.swing.JTextField();
        doc_ageLbl9 = new javax.swing.JLabel();
        doc_specialityTxt10 = new javax.swing.JTextField();
        doc_specialityLbl10 = new javax.swing.JLabel();
        doc_zipTxt11 = new javax.swing.JTextField();
        doc_zipLbl11 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jdoclistTable = new javax.swing.JTable();
        DeletedocBtn1 = new javax.swing.JButton();
        EditdocBtn1 = new javax.swing.JButton();
        ViewdocBtn1 = new javax.swing.JButton();
        NewHospitalSubmitbtn3 = new javax.swing.JButton();
        doc_nameLbl3 = new javax.swing.JLabel();
        doc_name = new javax.swing.JTextField();
        doc_CityLbl3 = new javax.swing.JLabel();
        doc_CityCb3 = new javax.swing.JComboBox<>();
        doc_HospitalLbl3 = new javax.swing.JLabel();
        doc_HospitalTxt3 = new javax.swing.JTextField();
        doc_ageTxt10 = new javax.swing.JTextField();
        doc_ageLbl10 = new javax.swing.JLabel();
        doc_specialistTxt11 = new javax.swing.JTextField();
        doc_specialistLbl11 = new javax.swing.JLabel();
        doc_zipTxt9 = new javax.swing.JTextField();
        doc_zipLbl9 = new javax.swing.JLabel();
        jPatientSysAdmin = new javax.swing.JPanel();
        jSplitPane3 = new javax.swing.JSplitPane();
        jPanel7 = new javax.swing.JPanel();
        NewpatientBtn2 = new javax.swing.JButton();
        DisplaypatientBtn1 = new javax.swing.JButton();
        patientBackBtn1 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        patient_nameLbl4 = new javax.swing.JLabel();
        patient_nameTxt1 = new javax.swing.JTextField();
        patient_CommunityLbl4 = new javax.swing.JLabel();
        patient_CommunityCb4 = new javax.swing.JComboBox<>();
        doc_Submitbtn3 = new javax.swing.JButton();
        patient_numberTxt = new javax.swing.JTextField();
        patient_cityComboBox1 = new javax.swing.JComboBox<>();
        patient_numberLbl = new javax.swing.JLabel();
        patient_cityLbl = new javax.swing.JLabel();
        patient_addressLbl = new javax.swing.JLabel();
        patient_addressTxt = new javax.swing.JTextField();
        patient_zipTxt = new javax.swing.JTextField();
        patient_zipLbl = new javax.swing.JLabel();
        patient_ageTxt9 = new javax.swing.JTextField();
        patient_ageLbl9 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jpatientlistTable1 = new javax.swing.JTable();
        DeletedocBtn2 = new javax.swing.JButton();
        EditdocBtn2 = new javax.swing.JButton();
        ViewdocBtn2 = new javax.swing.JButton();
        NewHospitalSubmitbtn4 = new javax.swing.JButton();
        patient_nameLbl5 = new javax.swing.JLabel();
        patient_name1 = new javax.swing.JTextField();
        patient_CommunityLbl5 = new javax.swing.JLabel();
        patient_CommunityCb5 = new javax.swing.JComboBox<>();
        patient_numTxt = new javax.swing.JTextField();
        patient_cityLbl11 = new javax.swing.JLabel();
        patient_numLbl = new javax.swing.JLabel();
        patient_addressTxt11 = new javax.swing.JTextField();
        patient_numLbl11 = new javax.swing.JLabel();
        patient_cityJComboBox = new javax.swing.JComboBox<>();
        patient_zipTxt12 = new javax.swing.JTextField();
        patient_zipLbl12 = new javax.swing.JLabel();
        patient_ageTxt8 = new javax.swing.JTextField();
        patient_ageLbl8 = new javax.swing.JLabel();
        jEncounterSysAdmin = new javax.swing.JPanel();
        jSplitPane4 = new javax.swing.JSplitPane();
        jPanel10 = new javax.swing.JPanel();
        NewdocBtn3 = new javax.swing.JButton();
        DisplaydocBtn2 = new javax.swing.JButton();
        docBackBtn2 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        doc_nameLbl6 = new javax.swing.JLabel();
        doc_CommunityLbl6 = new javax.swing.JLabel();
        doc_CommunityCb6 = new javax.swing.JComboBox<>();
        doc_HospitalLbl6 = new javax.swing.JLabel();
        doc_HospitalTxt6 = new javax.swing.JTextField();
        doc_Submitbtn4 = new javax.swing.JButton();
        doc_nameTxt2 = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jdoclistTable2 = new javax.swing.JTable();
        DeletedocBtn3 = new javax.swing.JButton();
        EditdocBtn3 = new javax.swing.JButton();
        ViewdocBtn3 = new javax.swing.JButton();
        NewHospitalSubmitbtn5 = new javax.swing.JButton();
        doc_nameLbl7 = new javax.swing.JLabel();
        doc_name2 = new javax.swing.JTextField();
        doc_CommunityLbl7 = new javax.swing.JLabel();
        doc_CommunityCb7 = new javax.swing.JComboBox<>();
        doc_HospitalLbl7 = new javax.swing.JLabel();
        doc_HospitalTxt7 = new javax.swing.JTextField();
        patientsearchBtn = new javax.swing.JButton();
        patientsearchTxt = new javax.swing.JTextField();
        patientseachLbl = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        hospitalSysAdminBtn.setText("Hospital");
        hospitalSysAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalSysAdminBtnActionPerformed(evt);
            }
        });

        patientSysAdminBtn.setText("Patient");
        patientSysAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientSysAdminBtnActionPerformed(evt);
            }
        });

        encounterSysAdminBtn.setText("Encounter");
        encounterSysAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encounterSysAdminBtnActionPerformed(evt);
            }
        });

        DoctorSysAdminBtn.setText("Doctor");
        DoctorSysAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorSysAdminBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLandingPanelLayout = new javax.swing.GroupLayout(jLandingPanel);
        jLandingPanel.setLayout(jLandingPanelLayout);
        jLandingPanelLayout.setHorizontalGroup(
            jLandingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLandingPanelLayout.createSequentialGroup()
                .addContainerGap(221, Short.MAX_VALUE)
                .addGroup(jLandingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(patientSysAdminBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hospitalSysAdminBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(115, 115, 115)
                .addGroup(jLandingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(encounterSysAdminBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DoctorSysAdminBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(114, 114, 114))
        );
        jLandingPanelLayout.setVerticalGroup(
            jLandingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLandingPanelLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addGroup(jLandingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hospitalSysAdminBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(encounterSysAdminBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(115, 115, 115)
                .addGroup(jLandingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientSysAdminBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DoctorSysAdminBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(265, Short.MAX_VALUE))
        );

        add(jLandingPanel, "card6");

        NewHospitalBtn.setText("Create");
        NewHospitalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewHospitalBtnActionPerformed(evt);
            }
        });

        DisplayHospitalBtn.setText("View");
        DisplayHospitalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayHospitalBtnActionPerformed(evt);
            }
        });

        HospitalBackBtn.setText("Back");
        HospitalBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HospitalBackBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DisplayHospitalBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NewHospitalBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HospitalBackBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(NewHospitalBtn)
                .addGap(39, 39, 39)
                .addComponent(DisplayHospitalBtn)
                .addGap(33, 33, 33)
                .addComponent(HospitalBackBtn)
                .addContainerGap(318, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jLabel1.setText("Create Hospital (JPanel 2])");

        CityHospitalLbl.setText("City");

        HospitalCommunityLbl.setText("Community");

        NewHospitalLbl.setText("Hospital");

        NewHospitalSubmitbtn.setText("Submit");
        NewHospitalSubmitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewHospitalSubmitbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(HospitalCommunityLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                    .addComponent(CityHospitalLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NewHospitalLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newHospitalTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(CityNewTxt)
                    .addComponent(CommunityNewTxt))
                .addGap(163, 163, 163))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(NewHospitalSubmitbtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CityHospitalLbl)
                    .addComponent(CityNewTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HospitalCommunityLbl)
                    .addComponent(CommunityNewTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewHospitalLbl)
                    .addComponent(newHospitalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(NewHospitalSubmitbtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel2);

        jLabel2.setText("Display Hospital (JPanel 3)");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "City", "Community", "Hospital"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        DeleteHospBtn.setText("Delete");

        EditHospBtn.setText("Edit");

        ViewHospBtn.setText("View");

        NewHospitalSubmitbtn1.setText("Submit");
        NewHospitalSubmitbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewHospitalSubmitbtn1ActionPerformed(evt);
            }
        });

        CityHospitalLbl1.setText("City");

        HospitalCommunityLbl1.setText("Community");

        NewHospitalLbl1.setText("Hospital");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(ViewHospBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EditHospBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DeleteHospBtn))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(HospitalCommunityLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CityHospitalLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NewHospitalLbl1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(newHospitalTxt1, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                            .addComponent(CommunityUpdateTxt)
                            .addComponent(CityUpdateTxt))))
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(NewHospitalSubmitbtn1)
                .addGap(231, 231, 231))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteHospBtn)
                    .addComponent(EditHospBtn)
                    .addComponent(ViewHospBtn))
                .addGap(67, 67, 67)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CityHospitalLbl1)
                    .addComponent(CityUpdateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HospitalCommunityLbl1)
                    .addComponent(CommunityUpdateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewHospitalLbl1)
                    .addComponent(newHospitalTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(NewHospitalSubmitbtn1)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel3);

        javax.swing.GroupLayout jHospitalSysAdminLayout = new javax.swing.GroupLayout(jHospitalSysAdmin);
        jHospitalSysAdmin.setLayout(jHospitalSysAdminLayout);
        jHospitalSysAdminLayout.setHorizontalGroup(
            jHospitalSysAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        jHospitalSysAdminLayout.setVerticalGroup(
            jHospitalSysAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        add(jHospitalSysAdmin, "card2");

        NewdocBtn1.setText("Create");
        NewdocBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewdocBtn1ActionPerformed(evt);
            }
        });

        DisplaydocBtn.setText("View");
        DisplaydocBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplaydocBtnActionPerformed(evt);
            }
        });

        docBackBtn.setText("Back");
        docBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docBackBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DisplaydocBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NewdocBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(docBackBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(NewdocBtn1)
                .addGap(39, 39, 39)
                .addComponent(DisplaydocBtn)
                .addGap(33, 33, 33)
                .addComponent(docBackBtn)
                .addContainerGap(318, Short.MAX_VALUE))
        );

        jSplitPane2.setLeftComponent(jPanel4);

        jLabel3.setText("Create doc (JPanel 2])");

        doc_nameLbl2.setText("Name");

        doc_CityLbl2.setText("City");

        doc_HospitalLbl2.setText("Hospital");

        doc_Submitbtn2.setText("Submit");
        doc_Submitbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doc_Submitbtn2ActionPerformed(evt);
            }
        });

        doc_nameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doc_nameTxtActionPerformed(evt);
            }
        });

        doc_ageTxt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doc_ageTxt9ActionPerformed(evt);
            }
        });

        doc_ageLbl9.setText("Age");

        doc_specialityLbl10.setText("Specialist");

        doc_zipLbl11.setText("Zip Code");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(doc_Submitbtn2))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(doc_CityLbl2, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                        .addComponent(doc_nameLbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(doc_HospitalLbl2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                                    .addComponent(doc_ageLbl9)
                                    .addComponent(doc_specialityLbl10)
                                    .addComponent(doc_zipLbl11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(doc_CityCb2, 0, 161, Short.MAX_VALUE)
                                    .addComponent(doc_HospitalTxt2)
                                    .addComponent(doc_nameTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(doc_ageTxt9)
                                    .addComponent(doc_specialityTxt10)
                                    .addComponent(doc_zipTxt11))
                                .addGap(151, 151, 151)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doc_nameLbl2)
                    .addComponent(doc_nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doc_ageTxt9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doc_ageLbl9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doc_specialityTxt10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doc_specialityLbl10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doc_CityCb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doc_CityLbl2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doc_zipTxt11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doc_zipLbl11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doc_HospitalTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doc_HospitalLbl2))
                .addGap(70, 70, 70)
                .addComponent(doc_Submitbtn2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane2.setRightComponent(jPanel5);

        jLabel4.setText("Display doctor (JPanel 3)");

        jdoclistTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Age", "Specialist", "City", "Zip Code", "Hospital"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jdoclistTable);

        DeletedocBtn1.setText("Delete");

        EditdocBtn1.setText("Edit");

        ViewdocBtn1.setText("View");

        NewHospitalSubmitbtn3.setText("Submit");
        NewHospitalSubmitbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewHospitalSubmitbtn3ActionPerformed(evt);
            }
        });

        doc_nameLbl3.setText("Name");

        doc_CityLbl3.setText("City");

        doc_HospitalLbl3.setText("Hospital");

        doc_ageLbl10.setText("Age");

        doc_specialistTxt11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doc_specialistTxt11ActionPerformed(evt);
            }
        });

        doc_specialistLbl11.setText("Specialist");

        doc_zipTxt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doc_zipTxt9ActionPerformed(evt);
            }
        });

        doc_zipLbl9.setText("Zip Code");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(ViewdocBtn1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EditdocBtn1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DeletedocBtn1))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(doc_CityLbl3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(doc_nameLbl3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(doc_HospitalLbl3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(doc_ageLbl10)
                            .addComponent(doc_specialistLbl11)
                            .addComponent(doc_zipLbl9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(doc_CityCb3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(doc_HospitalTxt3, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                            .addComponent(doc_name)
                            .addComponent(doc_ageTxt10)
                            .addComponent(doc_specialistTxt11)
                            .addComponent(doc_zipTxt9))))
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(NewHospitalSubmitbtn3)
                .addGap(229, 229, 229))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeletedocBtn1)
                    .addComponent(EditdocBtn1)
                    .addComponent(ViewdocBtn1))
                .addGap(64, 64, 64)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doc_nameLbl3)
                    .addComponent(doc_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doc_ageTxt10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doc_ageLbl10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doc_specialistTxt11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doc_specialistLbl11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doc_CityCb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doc_CityLbl3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doc_zipTxt9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doc_zipLbl9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doc_HospitalTxt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doc_HospitalLbl3))
                .addGap(32, 32, 32)
                .addComponent(NewHospitalSubmitbtn3)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        jSplitPane2.setRightComponent(jPanel6);

        javax.swing.GroupLayout jDoctorSysAdminLayout = new javax.swing.GroupLayout(jDoctorSysAdmin);
        jDoctorSysAdmin.setLayout(jDoctorSysAdminLayout);
        jDoctorSysAdminLayout.setHorizontalGroup(
            jDoctorSysAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );
        jDoctorSysAdminLayout.setVerticalGroup(
            jDoctorSysAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
        );

        add(jDoctorSysAdmin, "card3");

        NewpatientBtn2.setText("Create");
        NewpatientBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewpatientBtn2ActionPerformed(evt);
            }
        });

        DisplaypatientBtn1.setText("View");
        DisplaypatientBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplaypatientBtn1ActionPerformed(evt);
            }
        });

        patientBackBtn1.setText("Back");
        patientBackBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientBackBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DisplaypatientBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NewpatientBtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(patientBackBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(NewpatientBtn2)
                .addGap(39, 39, 39)
                .addComponent(DisplaypatientBtn1)
                .addGap(33, 33, 33)
                .addComponent(patientBackBtn1)
                .addContainerGap(318, Short.MAX_VALUE))
        );

        jSplitPane3.setLeftComponent(jPanel7);

        jLabel5.setText("create patient (JPanel 2])");

        patient_nameLbl4.setText("Name");

        patient_nameTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patient_nameTxt1ActionPerformed(evt);
            }
        });

        patient_CommunityLbl4.setText("Community");

        doc_Submitbtn3.setText("Submit");
        doc_Submitbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doc_Submitbtn3ActionPerformed(evt);
            }
        });

        patient_cityComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        patient_numberLbl.setText("Phone number");

        patient_cityLbl.setText("City");

        patient_addressLbl.setText("Address");

        patient_addressTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patient_addressTxtActionPerformed(evt);
            }
        });

        patient_zipTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patient_zipTxtActionPerformed(evt);
            }
        });

        patient_zipLbl.setText("Zip Code");

        patient_ageLbl9.setText("Age");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(patient_CommunityLbl4, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                .addComponent(patient_numberLbl)
                                .addComponent(patient_nameLbl4, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                            .addComponent(patient_zipLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patient_cityLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patient_addressLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patient_ageLbl9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(patient_numberTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                .addComponent(patient_nameTxt1, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(patient_CommunityCb4, 0, 121, Short.MAX_VALUE)
                            .addComponent(patient_cityComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(patient_zipTxt)
                            .addComponent(patient_addressTxt)
                            .addComponent(patient_ageTxt9))
                        .addGap(192, 192, 192))))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(doc_Submitbtn3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patient_nameLbl4)
                    .addComponent(patient_nameTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patient_ageTxt9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patient_ageLbl9))
                .addGap(6, 6, 6)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patient_numberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patient_numberLbl))
                .addGap(12, 12, 12)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patient_addressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patient_addressLbl))
                .addGap(6, 6, 6)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patient_zipTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patient_zipLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patient_cityComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patient_cityLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patient_CommunityCb4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patient_CommunityLbl4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(doc_Submitbtn3)
                .addGap(28, 28, 28))
        );

        jSplitPane3.setRightComponent(jPanel8);

        jLabel6.setText("Display patient (JPanel 3)");

        jpatientlistTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "age", "Address", "Community", "City"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jpatientlistTable1);

        DeletedocBtn2.setText("Delete");

        EditdocBtn2.setText("Edit");

        ViewdocBtn2.setText("View");

        NewHospitalSubmitbtn4.setText("Submit");
        NewHospitalSubmitbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewHospitalSubmitbtn4ActionPerformed(evt);
            }
        });

        patient_nameLbl5.setText("Name");

        patient_CommunityLbl5.setText("Community");

        patient_numTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patient_numTxtActionPerformed(evt);
            }
        });

        patient_cityLbl11.setText("City");

        patient_numLbl.setText("Phone number");

        patient_numLbl11.setText("Address");

        patient_cityJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        patient_zipTxt12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patient_zipTxt12ActionPerformed(evt);
            }
        });

        patient_zipLbl12.setText("Zip Code");

        patient_ageLbl8.setText("Age");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(ViewdocBtn2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EditdocBtn2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DeletedocBtn2))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(patient_nameLbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(patient_cityLbl11)
                                    .addComponent(patient_numLbl11)
                                    .addComponent(patient_zipLbl12)
                                    .addComponent(patient_numLbl)
                                    .addComponent(patient_ageLbl8)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(patient_CommunityLbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(patient_CommunityCb5, 0, 222, Short.MAX_VALUE)
                            .addComponent(patient_name1)
                            .addComponent(patient_numTxt)
                            .addComponent(patient_addressTxt11)
                            .addComponent(patient_zipTxt12)
                            .addComponent(patient_cityJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(patient_ageTxt8)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(NewHospitalSubmitbtn4)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeletedocBtn2)
                    .addComponent(EditdocBtn2)
                    .addComponent(ViewdocBtn2))
                .addGap(64, 64, 64)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patient_nameLbl5)
                    .addComponent(patient_name1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patient_ageTxt8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patient_ageLbl8))
                .addGap(9, 9, 9)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patient_numTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patient_numLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patient_addressTxt11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patient_numLbl11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patient_zipTxt12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patient_zipLbl12))
                .addGap(9, 9, 9)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patient_cityJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patient_cityLbl11))
                .addGap(9, 9, 9)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patient_CommunityCb5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patient_CommunityLbl5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NewHospitalSubmitbtn4)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jSplitPane3.setRightComponent(jPanel9);

        javax.swing.GroupLayout jPatientSysAdminLayout = new javax.swing.GroupLayout(jPatientSysAdmin);
        jPatientSysAdmin.setLayout(jPatientSysAdminLayout);
        jPatientSysAdminLayout.setHorizontalGroup(
            jPatientSysAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane3)
        );
        jPatientSysAdminLayout.setVerticalGroup(
            jPatientSysAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane3)
        );

        add(jPatientSysAdmin, "card4");

        NewdocBtn3.setText("Create");
        NewdocBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewdocBtn3ActionPerformed(evt);
            }
        });

        DisplaydocBtn2.setText("View");
        DisplaydocBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplaydocBtn2ActionPerformed(evt);
            }
        });

        docBackBtn2.setText("Back");
        docBackBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docBackBtn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DisplaydocBtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NewdocBtn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(docBackBtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(NewdocBtn3)
                .addGap(39, 39, 39)
                .addComponent(DisplaydocBtn2)
                .addGap(33, 33, 33)
                .addComponent(docBackBtn2)
                .addContainerGap(318, Short.MAX_VALUE))
        );

        jSplitPane4.setLeftComponent(jPanel10);

        jLabel7.setText("Create doc (JPanel 2])");

        doc_nameLbl6.setText("Name");

        doc_CommunityLbl6.setText("Community");

        doc_HospitalLbl6.setText("Hospital");

        doc_Submitbtn4.setText("Submit");
        doc_Submitbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doc_Submitbtn4ActionPerformed(evt);
            }
        });

        doc_nameTxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doc_nameTxt2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(doc_Submitbtn4))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(doc_CommunityLbl6, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                    .addComponent(doc_nameLbl6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(doc_HospitalLbl6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(doc_CommunityCb6, 0, 161, Short.MAX_VALUE)
                                    .addComponent(doc_HospitalTxt6)
                                    .addComponent(doc_nameTxt2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(151, 151, 151))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(doc_nameTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(doc_CommunityCb6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(doc_HospitalTxt6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(doc_nameLbl6)
                        .addGap(18, 18, 18)
                        .addComponent(doc_CommunityLbl6)
                        .addGap(18, 18, 18)
                        .addComponent(doc_HospitalLbl6)))
                .addGap(51, 51, 51)
                .addComponent(doc_Submitbtn4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane4.setRightComponent(jPanel11);

        jLabel8.setText("Display doctor (JPanel 3)");

        jdoclistTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Community", "Hospital"
            }
        ));
        jScrollPane4.setViewportView(jdoclistTable2);

        DeletedocBtn3.setText("Delete");

        EditdocBtn3.setText("Edit");

        ViewdocBtn3.setText("View");

        NewHospitalSubmitbtn5.setText("Submit");
        NewHospitalSubmitbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewHospitalSubmitbtn5ActionPerformed(evt);
            }
        });

        doc_nameLbl7.setText("Name");

        doc_CommunityLbl7.setText("Community");

        doc_HospitalLbl7.setText("Hospital");

        patientsearchBtn.setText("Search");
        patientsearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientsearchBtnActionPerformed(evt);
            }
        });

        patientsearchTxt.setText("jTextField1");

        patientseachLbl.setText("Enter Patient Name:");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(doc_CommunityLbl7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(doc_nameLbl7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(doc_HospitalLbl7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(doc_CommunityCb7, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(doc_HospitalTxt7, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                            .addComponent(doc_name2))))
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addComponent(NewHospitalSubmitbtn5)
                        .addGap(231, 231, 231))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(ViewdocBtn3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EditdocBtn3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DeletedocBtn3))
                            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel12Layout.createSequentialGroup()
                                    .addComponent(patientseachLbl)
                                    .addGap(18, 18, 18)
                                    .addComponent(patientsearchTxt)
                                    .addGap(18, 18, 18)
                                    .addComponent(patientsearchBtn))
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(54, 54, 54))))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(30, 30, 30)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientsearchBtn)
                    .addComponent(patientsearchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientseachLbl))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ViewdocBtn3)
                    .addComponent(EditdocBtn3)
                    .addComponent(DeletedocBtn3))
                .addGap(29, 29, 29)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doc_nameLbl7)
                    .addComponent(doc_name2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doc_CommunityCb7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doc_CommunityLbl7))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doc_HospitalLbl7)
                    .addComponent(doc_HospitalTxt7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(NewHospitalSubmitbtn5)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        jSplitPane4.setRightComponent(jPanel12);

        javax.swing.GroupLayout jEncounterSysAdminLayout = new javax.swing.GroupLayout(jEncounterSysAdmin);
        jEncounterSysAdmin.setLayout(jEncounterSysAdminLayout);
        jEncounterSysAdminLayout.setHorizontalGroup(
            jEncounterSysAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane4)
        );
        jEncounterSysAdminLayout.setVerticalGroup(
            jEncounterSysAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane4)
        );

        add(jEncounterSysAdmin, "card5");
    }// </editor-fold>//GEN-END:initComponents

    private void NewHospitalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewHospitalBtnActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(jPanel2);
    }//GEN-LAST:event_NewHospitalBtnActionPerformed

    private void DisplayHospitalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayHospitalBtnActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(jPanel3);
    }//GEN-LAST:event_DisplayHospitalBtnActionPerformed

    private void NewHospitalSubmitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewHospitalSubmitbtnActionPerformed
        // TODO add your handling code here:
        
        String city = CityNewTxt.getText();
        String community = CommunityNewTxt.getText();
        String hospital = newHospitalTxt.getText();
        
        if(city.equals("") || community.equals("") || hospital.equals("")){
            JOptionPane.showMessageDialog(this, "Please enter Valid Details");
        }
        
        
    }//GEN-LAST:event_NewHospitalSubmitbtnActionPerformed

    private void NewHospitalSubmitbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewHospitalSubmitbtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewHospitalSubmitbtn1ActionPerformed

    private void hospitalSysAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalSysAdminBtnActionPerformed
        // TODO add your handling code here:
        jLandingPanel.setVisible(false);
        jHospitalSysAdmin.setVisible(true);
        jDoctorSysAdmin.setVisible(false);
        jEncounterSysAdmin.setVisible(false);
        jPatientSysAdmin.setVisible(false);
    }//GEN-LAST:event_hospitalSysAdminBtnActionPerformed

        
    private void encounterSysAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encounterSysAdminBtnActionPerformed
        // TODO add your handling code here:
        jLandingPanel.setVisible(false);
        jHospitalSysAdmin.setVisible(false);
        jDoctorSysAdmin.setVisible(false);
        jEncounterSysAdmin.setVisible(true);
        jPatientSysAdmin.setVisible(false);
    }//GEN-LAST:event_encounterSysAdminBtnActionPerformed

    private void HospitalBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HospitalBackBtnActionPerformed
        // TODO add your handling code here:
        jLandingPanel.setVisible(true);
        jHospitalSysAdmin.setVisible(false);
        jDoctorSysAdmin.setVisible(false);
        jEncounterSysAdmin.setVisible(false);
        jPatientSysAdmin.setVisible(false);
    }//GEN-LAST:event_HospitalBackBtnActionPerformed

    private void NewdocBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewdocBtn1ActionPerformed
        // TODO add your handling code here:
        jSplitPane2.setRightComponent(jPanel5);
    }//GEN-LAST:event_NewdocBtn1ActionPerformed

    private void DisplaydocBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplaydocBtnActionPerformed
        // TODO add your handling code here:
        jSplitPane2.setRightComponent(jPanel6);
    }//GEN-LAST:event_DisplaydocBtnActionPerformed

    private void docBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docBackBtnActionPerformed
        // TODO add your handling code here:
        jLandingPanel.setVisible(true);
        jHospitalSysAdmin.setVisible(false);
        jDoctorSysAdmin.setVisible(false);
        jEncounterSysAdmin.setVisible(false);
        jPatientSysAdmin.setVisible(false);
    }//GEN-LAST:event_docBackBtnActionPerformed

    private void doc_Submitbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doc_Submitbtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doc_Submitbtn2ActionPerformed

    private void NewHospitalSubmitbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewHospitalSubmitbtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewHospitalSubmitbtn3ActionPerformed

    private void doc_nameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doc_nameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doc_nameTxtActionPerformed

    private void DoctorSysAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorSysAdminBtnActionPerformed
        // TODO add your handling code here:
        jLandingPanel.setVisible(false);
        jHospitalSysAdmin.setVisible(false);
        jDoctorSysAdmin.setVisible(true);
        jEncounterSysAdmin.setVisible(false);
        jPatientSysAdmin.setVisible(false);
    }//GEN-LAST:event_DoctorSysAdminBtnActionPerformed

    private void patientSysAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientSysAdminBtnActionPerformed
        // TODO add your handling code here:
        jLandingPanel.setVisible(false);
        jHospitalSysAdmin.setVisible(false);
        jDoctorSysAdmin.setVisible(false);
        jEncounterSysAdmin.setVisible(false);
        jPatientSysAdmin.setVisible(true);
    }//GEN-LAST:event_patientSysAdminBtnActionPerformed

    private void NewpatientBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewpatientBtn2ActionPerformed
        // TODO add your handling code here:
        jSplitPane3.setRightComponent(jPanel8);
    }//GEN-LAST:event_NewpatientBtn2ActionPerformed

    private void DisplaypatientBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplaypatientBtn1ActionPerformed
        // TODO add your handling code here:
        jSplitPane3.setRightComponent(jPanel9);
    }//GEN-LAST:event_DisplaypatientBtn1ActionPerformed

    private void patientBackBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientBackBtn1ActionPerformed
        // TODO add your handling code here:
        jLandingPanel.setVisible(true);
        jHospitalSysAdmin.setVisible(false);
        jDoctorSysAdmin.setVisible(false);
        jEncounterSysAdmin.setVisible(false);
        jPatientSysAdmin.setVisible(false);
    }//GEN-LAST:event_patientBackBtn1ActionPerformed

    private void doc_Submitbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doc_Submitbtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doc_Submitbtn3ActionPerformed

    private void patient_nameTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patient_nameTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patient_nameTxt1ActionPerformed

    private void NewHospitalSubmitbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewHospitalSubmitbtn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewHospitalSubmitbtn4ActionPerformed

    private void NewdocBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewdocBtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewdocBtn3ActionPerformed

    private void DisplaydocBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplaydocBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DisplaydocBtn2ActionPerformed

    private void docBackBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docBackBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_docBackBtn2ActionPerformed

    private void doc_Submitbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doc_Submitbtn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doc_Submitbtn4ActionPerformed

    private void doc_nameTxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doc_nameTxt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doc_nameTxt2ActionPerformed

    private void NewHospitalSubmitbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewHospitalSubmitbtn5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewHospitalSubmitbtn5ActionPerformed

    private void patient_addressTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patient_addressTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patient_addressTxtActionPerformed

    private void patient_zipTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patient_zipTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patient_zipTxtActionPerformed

    private void patient_zipTxt12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patient_zipTxt12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patient_zipTxt12ActionPerformed

    private void patient_numTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patient_numTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patient_numTxtActionPerformed

    private void doc_ageTxt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doc_ageTxt9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doc_ageTxt9ActionPerformed

    private void doc_specialistTxt11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doc_specialistTxt11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doc_specialistTxt11ActionPerformed

    private void doc_zipTxt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doc_zipTxt9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doc_zipTxt9ActionPerformed

    private void patientsearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientsearchBtnActionPerformed
        // TODO add your handling code here:
        String patientName = patientsearchBtn.getText();
        ArrayList<Encounter> tmpHistory = new ArrayList<Encounter>();
        if(patientName.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Enter Valid Patient Name");
        }
        for(Encounter encounter : Encounterhistory.getEhistory()){
            if(patientName.equals(encounter.getPname())){
                tmpHistory.add(encounter);
            }
        }
        
        //getTableData(tmpHistory);
    }//GEN-LAST:event_patientsearchBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CityHospitalLbl;
    private javax.swing.JLabel CityHospitalLbl1;
    private javax.swing.JTextField CityNewTxt;
    private javax.swing.JTextField CityUpdateTxt;
    private javax.swing.JTextField CommunityNewTxt;
    private javax.swing.JTextField CommunityUpdateTxt;
    private javax.swing.JButton DeleteHospBtn;
    private javax.swing.JButton DeletedocBtn1;
    private javax.swing.JButton DeletedocBtn2;
    private javax.swing.JButton DeletedocBtn3;
    private javax.swing.JButton DisplayHospitalBtn;
    private javax.swing.JButton DisplaydocBtn;
    private javax.swing.JButton DisplaydocBtn2;
    private javax.swing.JButton DisplaypatientBtn1;
    private javax.swing.JButton DoctorSysAdminBtn;
    private javax.swing.JButton EditHospBtn;
    private javax.swing.JButton EditdocBtn1;
    private javax.swing.JButton EditdocBtn2;
    private javax.swing.JButton EditdocBtn3;
    private javax.swing.JButton HospitalBackBtn;
    private javax.swing.JLabel HospitalCommunityLbl;
    private javax.swing.JLabel HospitalCommunityLbl1;
    private javax.swing.JButton NewHospitalBtn;
    private javax.swing.JLabel NewHospitalLbl;
    private javax.swing.JLabel NewHospitalLbl1;
    private javax.swing.JButton NewHospitalSubmitbtn;
    private javax.swing.JButton NewHospitalSubmitbtn1;
    private javax.swing.JButton NewHospitalSubmitbtn3;
    private javax.swing.JButton NewHospitalSubmitbtn4;
    private javax.swing.JButton NewHospitalSubmitbtn5;
    private javax.swing.JButton NewdocBtn1;
    private javax.swing.JButton NewdocBtn3;
    private javax.swing.JButton NewpatientBtn2;
    private javax.swing.JButton ViewHospBtn;
    private javax.swing.JButton ViewdocBtn1;
    private javax.swing.JButton ViewdocBtn2;
    private javax.swing.JButton ViewdocBtn3;
    private javax.swing.JButton docBackBtn;
    private javax.swing.JButton docBackBtn2;
    private javax.swing.JComboBox<String> doc_CityCb2;
    private javax.swing.JComboBox<String> doc_CityCb3;
    private javax.swing.JLabel doc_CityLbl2;
    private javax.swing.JLabel doc_CityLbl3;
    private javax.swing.JComboBox<String> doc_CommunityCb6;
    private javax.swing.JComboBox<String> doc_CommunityCb7;
    private javax.swing.JLabel doc_CommunityLbl6;
    private javax.swing.JLabel doc_CommunityLbl7;
    private javax.swing.JLabel doc_HospitalLbl2;
    private javax.swing.JLabel doc_HospitalLbl3;
    private javax.swing.JLabel doc_HospitalLbl6;
    private javax.swing.JLabel doc_HospitalLbl7;
    private javax.swing.JTextField doc_HospitalTxt2;
    private javax.swing.JTextField doc_HospitalTxt3;
    private javax.swing.JTextField doc_HospitalTxt6;
    private javax.swing.JTextField doc_HospitalTxt7;
    private javax.swing.JButton doc_Submitbtn2;
    private javax.swing.JButton doc_Submitbtn3;
    private javax.swing.JButton doc_Submitbtn4;
    private javax.swing.JLabel doc_ageLbl10;
    private javax.swing.JLabel doc_ageLbl9;
    private javax.swing.JTextField doc_ageTxt10;
    private javax.swing.JTextField doc_ageTxt9;
    private javax.swing.JTextField doc_name;
    private javax.swing.JTextField doc_name2;
    private javax.swing.JLabel doc_nameLbl2;
    private javax.swing.JLabel doc_nameLbl3;
    private javax.swing.JLabel doc_nameLbl6;
    private javax.swing.JLabel doc_nameLbl7;
    private javax.swing.JTextField doc_nameTxt;
    private javax.swing.JTextField doc_nameTxt2;
    private javax.swing.JLabel doc_specialistLbl11;
    private javax.swing.JTextField doc_specialistTxt11;
    private javax.swing.JLabel doc_specialityLbl10;
    private javax.swing.JTextField doc_specialityTxt10;
    private javax.swing.JLabel doc_zipLbl11;
    private javax.swing.JLabel doc_zipLbl9;
    private javax.swing.JTextField doc_zipTxt11;
    private javax.swing.JTextField doc_zipTxt9;
    private javax.swing.JButton encounterSysAdminBtn;
    private javax.swing.JButton hospitalSysAdminBtn;
    private javax.swing.JPanel jDoctorSysAdmin;
    private javax.swing.JPanel jEncounterSysAdmin;
    private javax.swing.JPanel jHospitalSysAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jLandingPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPatientSysAdmin;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JSplitPane jSplitPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jdoclistTable;
    private javax.swing.JTable jdoclistTable2;
    private javax.swing.JTable jpatientlistTable1;
    private javax.swing.JTextField newHospitalTxt;
    private javax.swing.JTextField newHospitalTxt1;
    private javax.swing.JButton patientBackBtn1;
    private javax.swing.JButton patientSysAdminBtn;
    private javax.swing.JComboBox<String> patient_CommunityCb4;
    private javax.swing.JComboBox<String> patient_CommunityCb5;
    private javax.swing.JLabel patient_CommunityLbl4;
    private javax.swing.JLabel patient_CommunityLbl5;
    private javax.swing.JLabel patient_addressLbl;
    private javax.swing.JTextField patient_addressTxt;
    private javax.swing.JTextField patient_addressTxt11;
    private javax.swing.JLabel patient_ageLbl8;
    private javax.swing.JLabel patient_ageLbl9;
    private javax.swing.JTextField patient_ageTxt8;
    private javax.swing.JTextField patient_ageTxt9;
    private javax.swing.JComboBox<String> patient_cityComboBox1;
    private javax.swing.JComboBox<String> patient_cityJComboBox;
    private javax.swing.JLabel patient_cityLbl;
    private javax.swing.JLabel patient_cityLbl11;
    private javax.swing.JTextField patient_name1;
    private javax.swing.JLabel patient_nameLbl4;
    private javax.swing.JLabel patient_nameLbl5;
    private javax.swing.JTextField patient_nameTxt1;
    private javax.swing.JLabel patient_numLbl;
    private javax.swing.JLabel patient_numLbl11;
    private javax.swing.JTextField patient_numTxt;
    private javax.swing.JLabel patient_numberLbl;
    private javax.swing.JTextField patient_numberTxt;
    private javax.swing.JLabel patient_zipLbl;
    private javax.swing.JLabel patient_zipLbl12;
    private javax.swing.JTextField patient_zipTxt;
    private javax.swing.JTextField patient_zipTxt12;
    private javax.swing.JLabel patientseachLbl;
    private javax.swing.JButton patientsearchBtn;
    private javax.swing.JTextField patientsearchTxt;
    // End of variables declaration//GEN-END:variables
}
